#! /bin/sh

#create dataverse and datasets
curl -H "Accept: application/x-adm" -v --data-urlencode 'statement=drop dataverse steven if exists;
create dataverse steven;
use steven;

create type UserLocation as {
	location: circle,
	userName: string,
	timeStamp: datetime
};


create type UserLocationFeedType as {
	location: circle,
	userName: string
};

create type EmergencyReport as {
	reportId: uuid,
	Etype: string,
	location: circle,
	timeStamp: datetime
};

create type EmergencyReportFeedType as {
	Etype: string,
	location: circle
};


create type EmergencyShelter as {
	shelterName: string,
	location: point
};

create dataset UserLocations(UserLocation)
primary key userName;
create dataset Shelters(EmergencyShelter)
primary key shelterName;
create dataset Reports(EmergencyReport)
primary key reportId autogenerated;

create index location_time on UserLocations(timeStamp);
create index u_location on UserLocations(location) type RTREE;
create index s_location on Shelters(location) type RTREE;
create index report_time on Reports(timeStamp);

create function add_insert_time(record) {
    object_merge({"timeStamp": current_datetime()}, record)
};

' http://promethium.ics.uci.edu:19002/query/service > responses/responses.txt

curl -H "Accept: application/x-adm" -v --data-urlencode 'statement=use steven;
LOAD DATASET Reports USING localfs
 (("path"="promethium.ics.uci.edu:///home/asterix/three/EmergenciesBulk.adm"),("format"="adm"));
' http://promethium.ics.uci.edu:19002/query/service > responses/responses.txt


curl -H "Accept: application/x-adm" -v --data-urlencode 'statement=use steven;
create feed ReportFeed with
{
	"adapter-name" : "socket_adapter",
    "sockets" : "promethium.ics.uci.edu:10008",
    "address-type" : "IP",
    "type-name" : "EmergencyReportFeedType",
    "format" : "adm"
};
' http://promethium.ics.uci.edu:19002/query/service > responses/responses.txt

curl -H "Accept: application/x-adm" -v --data-urlencode 'statement=use steven;
create feed LocationFeed with
{
	"adapter-name" : "socket_adapter",
    "sockets" : "promethium.ics.uci.edu:10009",
    "address-type" : "IP",
    "type-name" : "UserLocationFeedType",
    "format" : "adm"
};
' http://promethium.ics.uci.edu:19002/query/service > responses/responses.txt

curl -H "Accept: application/x-adm" -v --data-urlencode 'statement=use steven;
connect feed ReportFeed to dataset Reports apply function add_insert_time;
' http://promethium.ics.uci.edu:19002/query/service > responses/responses.txt

curl -H "Accept: application/x-adm" -v --data-urlencode 'statement=use steven;
connect feed LocationFeed to dataset UserLocations apply function add_insert_time;
' http://promethium.ics.uci.edu:19002/query/service > responses/responses.txt


curl -H "Accept: application/x-adm" -v --data-urlencode 'statement=use steven;
start feed LocationFeed;
start feed ReportFeed;
' http://promethium.ics.uci.edu:19002/query/service > responses/responses.txt

curl -H "Accept: application/x-adm" -v --data-urlencode 'statement=use steven;
LOAD DATASET Shelters USING localfs
 (("path"="promethium.ics.uci.edu:///home/asterix/three/shelters/Shelters200s0.adm"),("format"="adm"));
' http://promethium.ics.uci.edu:19002/query/service > responses/responses.txt
